language: python
python:
- '3.6'
cache: pip
install: pip install -r requirements.txt
script: python tests.py
before_install:
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key fjl2202@alfred.eecs.northwestern.edu pwd