language: python
python:
- '3.6'
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy-key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy-key
  - ssh -i ./deploy-key fjl2202@alfred.eecs.northwestern.edu pwd
cache: pip
install: pip install -r requirements.txt
script: python tests.py
before_install:
  - openssl aes-256-cbc -K $encrypted_f8b46c6fada5_key -iv $encrypted_f8b46c6fada5_iv
    -in deploy-key.enc -out ./deploy-key -d
  - ssh-add ./deploy-key
