language: python
python:
- '3.6'
cache: pip
install: pip install -r requirements.txt
script: python tests.py
before_install:
- openssl aes-256-cbc -K $encrypted_f8b46c6fada5_key -iv $encrypted_f8b46c6fada5_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key fjl2202@alfred.eecs.northwestern.edu pwd