language: python
python:
- '3.6'
cache: pip
install: pip install -r requirements.txt
script: python tests.py
addons:
  ssh_known_hosts:
  - alfred.eecs.northwestern.edu
before_install:
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host alfred.eecs.northwestern.edu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- scp -i deploy_key assignment3.py fjl2202@alfred.eecs.northwestern.edu:assignment3
- ssh -i deploy_key fjl2202@alfred.eecs.northwestern.edu cd assignment3 && python $PWD/assignment3/test.py
- ssh -i deploy_key fjl2202@alfred.eecs.northwestern.edu rm assignment3/assignment3.py